### ISSUE TITLE
Next.js: cannot find module intl-tel-input/react or its corresponding type declarations

### ISSUE THREAD

**Issue by qinfengwu90** [jackocnr/intl-tel-input#1558]
### Steps to reproduce
1.  used `yarn add intl-tel-input` to install the latest version 21.0.5
2.  tried both Webstorm and VS Code
3.  also installed `"@types/intl-tel-input": "^18.1.4"` and imported `"intl-tel-input/build/js/types.d.ts"`;
`

### Expected behaviour
It should import the `IntlTelInput` React component

### Actual behaviour
IDE says they couldn't find the module 

<img width="1025" alt="Screenshot 2024-04-05 at 09 40 21" src="https://github.com/jackocnr/intl-tel-input/assets/45974309/5e477567-48e1-4b1e-86b0-b17dc0b13dbd">
<img width="935" alt="Screenshot 2024-04-05 at 09 39 35" src="https://github.com/jackocnr/intl-tel-input/assets/45974309/e44aebf2-70d5-4fef-b733-ef43f03a2712">

Thanks for looking into it

**Comment by jackocnr** [comment]
Thanks for reporting this. Unfortunately, I cannot reproduce the issue - I just created a new Next.js project with `npx create-next-app@latest` (which uses Next.js v14.1.4) and then did `npm install --save intl-tel-input` and then imported the plugin with `import IntlTelInput from "intl-tel-input/react"` and it works fine for me. I do get a linting error saying "Could not find a declaration file for module 'intl-tel-input/react'" (this is a known issue) but the dev build works fine and successfully displays the plugin on the page.

Some questions for you:

- What version of Next.js are you using? (and Node version too)
- Can you share your Next config
- And your TSconfig as well
- And any custom Webpack config too if you have one

**Comment by jackocnr** [comment]
In v21.0.6 I've fixed the "Could not find a declaration file" error.

**Comment by qinfengwu90** [comment]
> Thanks for reporting this. Unfortunately, I cannot reproduce the issue - I just created a new Next.js project with `npx create-next-app@latest` (which uses Next.js v14.1.4) and then did `npm install --save intl-tel-input` and then imported the plugin with `import IntlTelInput from "intl-tel-input/react"` and it works fine for me. ~I do get a linting error saying "Could not find a declaration file for module 'intl-tel-input/react'" (this is a known issue) but the dev build works fine and successfully displays the plugin on the page.~ (Fixed in v21.0.6)
> 
> Some questions for you:
> 
> * What version of Next.js are you using? (and Node version too)
> * Can you share your Next config
> * And your TSconfig as well
> * And any custom Webpack config too if you have one

Thanks for looking into it. Here is the specific info:
- Next.js v13.2.4
- Node v21.6.2
- next.config.js
```javascript
const withBundleAnalyzer = require("@next/bundle-analyzer")({
  enabled: process.env.ANALYZE === "true",
});

if (
  process.env.LD_LIBRARY_PATH == null ||
  !process.env.LD_LIBRARY_PATH.includes(
    `${process.env.PWD}/node_modules/canvas/build/Release:`
  )
) {
  process.env.LD_LIBRARY_PATH = `${
    process.env.PWD
  }/node_modules/canvas/build/Release:${process.env.LD_LIBRARY_PATH || ""}`;
}

/** @type {import('next').NextConfig} */
const nextConfig = {
  experimental: {
    appDir: false,
  },
  images: {
    domains: [
      "cloudflare-ipfs.com",
      "gcqrvlegvyiunwewkuoz.supabase.co",
      "ordynhmcwwnczgnvuomz.supabase.co",
    ],
  },
  output: "standalone",
  webpack: (config) => {
    config.mode = "production";
    config.module.rules.push({
      test: /\.pdf/,
      type: "asset/resource",
      generator: {
        filename: "static/[hash][ext]",
      },
    });

    return config;
  },
  async redirects() {
    return [
      {
        source: "/onboarding",
        destination: "/onboarding/region-screen",
        permanent: true,
      },
      {
        source: "/profile",
        destination: "/patient-portal/profile",
        permanent: true,
      },
      {
        source: "/update-payment",
        destination: "/patient-portal/profile/update-payment",
        permanent: true,
      },
    ];
  },
};

module.exports = withBundleAnalyzer(nextConfig);
``` 
- tsconfig.json
```javascript
{
  "compilerOptions": {
    "target": "es2015",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "noEmit": true,
    "noImplicitAny": true,
    "noImplicitThis": true,
    "strictNullChecks": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "plugins": [
      {
        "name": "next"
      }
    ],
    "baseUrl": ".",
    "paths": {
      "@/*": ["./src/*"]
    }
  },
  "include": [
    "next-env.d.ts",
    "**/*.ts",
    "**/*.tsx",
    ".next/types/**/*.ts",
    "src/types",
    "additional.d.ts",
    "global.d.ts",
    "src/pages/_document.tsx"
  ],
  "exclude": ["node_modules"]
}
``` 
- webpack 5.76.0

I just installed the latest version v21.0.6. The error in the first screenshot still persists, but the error in the second screenshot is gone. 

When I do `npm run dev`, I received the following error

<img width="1019" alt="Screenshot 2024-04-06 at 07 51 32" src="https://github.com/jackocnr/intl-tel-input/assets/45974309/effe4ab2-a217-45e5-af2c-28eebd788b0d">

```
SyntaxError: Cannot use import statement outside a module
    at internalCompileFunction (node:internal/vm:77:18)
    at wrapSafe (node:internal/modules/cjs/loader:1290:20)
    at Module._compile (node:internal/modules/cjs/loader:1342:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1437:10)
    at Module.load (node:internal/modules/cjs/loader:1212:32)
    at Module._load (node:internal/modules/cjs/loader:1028:12)
    at Module.require (node:internal/modules/cjs/loader:1237:19)
    at require (node:internal/modules/helpers:176:18)
    at 8598 (/Users/qinfengwu/WebstormProjects/frontend-next/.next/server/pages/onboarding/complete-profile.js:1346:18)
    at __webpack_require__ (/Users/qinfengwu/WebstormProjects/frontend-next/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///6692:32:79)
    at __webpack_require__.a (/Users/qinfengwu/WebstormProjects/frontend-next/.next/server/webpack-runtime.js:97:13)
    at eval (webpack-internal:///6692:1:21)
    at 6692 (/Users/qinfengwu/WebstormProjects/frontend-next/.next/server/pages/onboarding/complete-profile.js:304:1)
    at __webpack_require__ (/Users/qinfengwu/WebstormProjects/frontend-next/.next/server/webpack-runtime.js:33:42)
    at /Users/qinfengwu/WebstormProjects/frontend-next/.next/server/pages/onboarding/complete-profile.js:317:77
    at __webpack_require__.a (/Users/qinfengwu/WebstormProjects/frontend-next/.next/server/webpack-runtime.js:97:13)
    at 467 (/Users/qinfengwu/WebstormProjects/frontend-next/.next/server/pages/onboarding/complete-profile.js:312:21)
    at __webpack_require__ (/Users/qinfengwu/WebstormProjects/frontend-next/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///8933:10:88)
    at __webpack_require__.a (/Users/qinfengwu/WebstormProjects/frontend-next/.next/server/webpack-runtime.js:97:13)
    at eval (webpack-internal:///8933:1:21)
    at 8933 (/Users/qinfengwu/WebstormProjects/frontend-next/.next/server/pages/onboarding/complete-profile.js:296:1)
    at __webpack_require__ (/Users/qinfengwu/WebstormProjects/frontend-next/.next/server/webpack-runtime.js:33:42)
    at /Users/qinfengwu/WebstormProjects/frontend-next/.next/server/pages/onboarding/complete-profile.js:335:73
    at __webpack_require__.a (/Users/qinfengwu/WebstormProjects/frontend-next/.next/server/webpack-runtime.js:97:13)
    at 4937 (/Users/qinfengwu/WebstormProjects/frontend-next/.next/server/pages/onboarding/complete-profile.js:330:21)
    at __webpack_require__ (/Users/qinfengwu/WebstormProjects/frontend-next/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///3751:11:92)
    at __webpack_require__.a (/Users/qinfengwu/WebstormProjects/frontend-next/.next/server/webpack-runtime.js:97:13)
    at eval (webpack-internal:///3751:1:21)
    at 3751 (/Users/qinfengwu/WebstormProjects/frontend-next/.next/server/pages/onboarding/complete-profile.js:1054:1)
    at __webpack_require__ (/Users/qinfengwu/WebstormProjects/frontend-next/.next/server/webpack-runtime.js:33:42)
    at __webpack_exec__ (/Users/qinfengwu/WebstormProjects/frontend-next/.next/server/pages/onboarding/complete-profile.js:2492:39)
    at /Users/qinfengwu/WebstormProjects/frontend-next/.next/server/pages/onboarding/complete-profile.js:2493:28
    at Object.<anonymous> (/Users/qinfengwu/WebstormProjects/frontend-next/.next/server/pages/onboarding/complete-profile.js:2496:3)
    at Module._compile (node:internal/modules/cjs/loader:1378:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1437:10)
    at Module.load (node:internal/modules/cjs/loader:1212:32)
    at Module._load (node:internal/modules/cjs/loader:1028:12)
    at Module.require (node:internal/modules/cjs/loader:1237:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.requirePage (/Users/qinfengwu/WebstormProjects/frontend-next/node_modules/next/dist/server/require.js:88:12)
    at /Users/qinfengwu/WebstormProjects/frontend-next/node_modules/next/dist/server/load-components.js:49:73
    at async Object.loadComponentsImpl [as loadComponents] (/Users/qinfengwu/WebstormProjects/frontend-next/node_modules/next/dist/server/load-components.js:49:26)
    at async DevServer.findPageComponentsImpl (/Users/qinfengwu/WebstormProjects/frontend-next/node_modules/next/dist/server/next-server.js:600:36) {
  page: '/onboarding/complete-profile'
}
```

**Comment by jackocnr** [comment]
> also installed "@types/intl-tel-input": "^18.1.4" and imported "intl-tel-input/build/js/types.d.ts"

You shouldn't need either of these any more - can you try removing them both and see if that changes anything?

**Comment by b4ry** [comment]
Getting the same issues in a react 18x app.
Cannot import **intl-tel-input/react**, but **intl-tel-input** works fine.
I did not install any types.

**Comment by jackocnr** [comment]
Thanks for reporting @b4ry. Are you also using Typescript? Which version? And can you share your tsconfig?

And @qinfengwu90 which version of Typescript are you using?

**Comment by qinfengwu90** [comment]
> > also installed "@types/intl-tel-input": "^18.1.4" and imported "intl-tel-input/build/js/types.d.ts"
> 
> You shouldn't need either of these any more - can you try removing them both and see if that changes anything?

I removed those and it didn't change anything.

The Typescript version is 4.9.5

**Comment by qinfengwu90** [comment]
It works now! Thank you very much.

**Comment by jackocnr** [comment]
I'll close this issue for now, but @b4ry do let me know if you're still having problems.

**Comment by b4ry** [comment]
@jackocnr 
Hey!
I updated to v21.1.1 and it is working like a charm now. Thanks!

**Comment by moos** [comment]
Hi -- I'm seeing this issue with `intl-tel-input@23.1.0`. Seeing this with **eslint** and **jest**, but the app itself is working.
```
│ └── eslint@6.8.0 deduped
├── intl-tel-input@23.1.0
└── jest@27.0.6
```
```
 Cannot find module 'intl-tel-input/react' from ...
```
Appreciate any guidance here.

**Comment by jackocnr** [comment]
> Seeing this with eslint and jest, but the app itself (using webpack) is working.

Can you clarify exactly what you mean by this? What command(s) are you running when you get the error?

Can you try updating Eslint and Jest to the latest version? And if you're still seeing the error, then can you share your related config files?

**Comment by moos** [comment]
For `jest` it's related to this issue: https://github.com/jestjs/jest/issues/9771 -- that version didn't support `exports` declaration in `package.json`. Updating to jest 29.x fixed the issue. I suspect issue with `eslint` is similar.
