### ISSUE TITLE
initial country fixed or auto does not have the same behavior

### ISSUE THREAD

**Issue by cyrilchampier** [jackocnr/intl-tel-input#408]
### Steps to reproduce
set field value to something wrong
set params to  `{ initialCountry: 'auto', geoIpLookup: function(callback) { callback('us'); } }`

### Expected behaviour
The selected country should be 'us', just as if the params where
`{ initialCountry: 'us' }`

### Actual behaviour
Country is not filled, therefore cause errors later on `.intlTelInput("getNumber")`

### Initialisation options
all default except specified.

**Comment by jackocnr** [comment]
Confirmed: http://codepen.io/jackocnr/pen/mPGrZP 

Thank you.

FYI I'm open to a pull request to fix this, as I don't know when I will have time to look into it.

**Comment by cyrilchampier** [comment]
thanks @jackocnr 
what would be the correct behavior for that ?
for us, we already have an existing database, and we dont want to force the country for those existing values.
maybe the auto behavior is the good one: only set value if it's undefined, not if it's blank ?
or should we add a param ?

`initialCountry` sound like 'overwrite existing value by this one'

maybe
`defaultCountry`: 'put this value if the existing one is undefined'
`defaultCountryOverwriteBlanks`: 'should the defaultCountry be set for defined by invalid values (default to true to keep current behavior)'

what do you think ?

**Comment by jackocnr** [comment]
Oh I remember now, the assumption is: if you already have the number, then it's your responsibility to set the country too. You do this via the `initialCountry` option. I will add a note about this in the readme.

I don't think the `geoIpLookup` should force it's result on an existing number because it could be wrong. I will also add a note about this in the readme.

So actually I think the current behavior is working as expected. In your case, I would advise you use the following logic: if you already have a number when you initialize the plugin, then set initialCountry accordingly, and only if you don't already have a number: set it to "auto".

I also intend to add a Recommended Usage section to the readme, which says that: even when `nationalMode` or `separateDialCode` is enabled, the plugin is built to deal with numbers in the E.164 standard format (full international numbers including country codes) and convert them accordingly. I recommend you get, store, and set numbers in this format for simplicity. You can get the full number using `getNumber`, then you only have to store one string in your database, and then when you want to initialise the plugin again, you can either set that full number as the input's value, or you can use `setNumber` and either way it saves you having to set the country separately.

Does that make sense?

**Comment by cyrilchampier** [comment]
Yep it is.
But to be totally explicit, the `geoIpLookup` could be renamed in `defaultCountry` which take a value or a function.
`initialCountry` would overwrite existing undefined or blank values
`defaultCountry` would select the country if undefined (but not if blank)

no ?

**Comment by jackocnr** [comment]
So you're suggesting in your case, you would set initialCountry to "auto", AND defaultCountry to "us"? I think that's even more confusing.

I think that what I proposed before makes more sense. It would look something like this.

```js
$("#phone").intlTelInput({
    initialCountry: user.country || "auto",
    geoIpLookup: function() {...}
});
```

**Comment by jackocnr** [comment]
Hmm maybe I misunderstood what you were saying. Please can you explain more what you mean, and give an example?

**Comment by cyrilchampier** [comment]
hum in fact i am lost myself :)

what about:
* `initialCountry` would fill the country if 'the whole number is empty' (== country undefined)
* `defaultCountry` would fill the country if 'the whole number is empty, or if the country is not selected' (== country blank)
and both could take a static country code or a function.

but that still let space for confusion...

**Comment by jackocnr** [comment]
Do you think my proposed solution (see code above) would not work for you? And if not, then why?

**Comment by cyrilchampier** [comment]
your solution works perfectly, and in fact, you are right, a simple readme explanation on the `auto` keyword would be sufficient.
I was just digging to find disambiguation over this keyword that means both things:
`search with a function` and `do fill only if no number`

**Comment by jackocnr** [comment]
Ok I've updated the readme. Please let me know if anything is not clear! Thanks.

**Comment by silent-e** [comment]
for posterity, here's how I was able to get around this problem.  We don't know the user's country so we couldn't use the solution from @jackocnr.  It's a hack but it works.  Even 10ms is enough.  Without the timeout I'm still not seeing the dropdown change.

````js
$("phone").intlTelInput({
  initialCountry: "auto",
  geoIpLookup: function(callback) {
    var elt = document.getElementById('phone'),
        current_value = elt.value;
    elt.value = '';  // unset the value before checking geoip
    $.get('https://ipinfo.io', function() {}, "jsonp").always(function(resp) {
      var countryCode = (resp && resp.country) ? resp.country : "";
      callback(countryCode);
      setTimeout(function() {
        elt.value = current_value;  // set value back after geoip is done.
      }, 10);
    });
  },
  utilsScript: "/assets/utils.js"
});
````

**Comment by jackocnr** [comment]
@silent-e sure, if you know for certain the phone number is for the country the user is currently in (and they're not going through any kind of proxy).

**Comment by jackocnr** [comment]
Otherwise I highly recommend you either store the number in standard international format (including the international dial code), or store the country code as well, so that when displaying the number again, you can be sure you set the correct country.

**Comment by silent-e** [comment]
got it.  thanks for pointing that out.

**Comment by soumyaranjansia** [comment]
here is the code how we can fix this:

i dont want to explain but checkout this below:

```
function getUserCountryCode(callback) {
            if (navigator.geolocation) {
                navigator.geolocation.getCurrentPosition(function (position) {
                    // Use latitude and longitude to determine the country
                    var latitude = position.coords.latitude;
                    var longitude = position.coords.longitude;

                    // Use ip-api.com for reverse geocoding to get country information
                    fetch(`http://ip-api.com/json/`)
                        .then(function (response) {
                            return response.json();
                        })
                        .then(function (data) {
                            var countryCode = data.countryCode;
                            callback(countryCode);
                        })
                        .catch(function (error) {
                            console.error('Error fetching country code:', error);
                            callback('');
                        });
                }, function (error) {
                    console.error('Error getting geolocation:', error);
                    callback('');
                });
            } else {
                console.error('Geolocation is not supported by this browser.');
                callback('');
            }
        }

        // Initialize the plugin after retrieving or using the obtained country code
        function initializePhoneNumberInput() {
            getUserCountryCode(function (countryCode) {
                var input = document.querySelector("#phone");
                var iti = window.intlTelInput(input, {
                    initialCountry: countryCode || 'auto', // Use the retrieved country code or 'auto'
                    separateDialCode: true, // Display the country dial code separately
                    utilsScript: "https://cdn.jsdelivr.net/npm/intl-tel-input@18.2.1/build/js/utils.js"
                });

                // Set the selected country after initialization
                iti.setCountry(countryCode || 'auto');
            });
        }

        // Call initialize function when the page loads
        initializePhoneNumberInput();

        // Update country code when the window resizes
        window.addEventListener('resize', function () {
            // Destroy the previous instance
            var input = document.querySelector("#phone");
            input.intlTelInput('destroy');

            // Re-initialize the input
            initializePhoneNumberInput();
        });
```

i think it will help you
